### ISSUE TITLE
user story 17 / migrate typescript

### ISSUE THREAD

**Issue by alperkuertuel** [alperkuertuel/saba-art#87]
## Value proposition

As a developer
I want to migrate typescript
In order to have type safety

## Acceptance criteria

- [ ] the repo has type safety
- [ ] maintainability is enhanced

## Tasks

- [ ] read about next.js with typescript
- [ ] install typescript
- [ ] setup tsconfig.ts 
- [ ] rename files and create typesafety

## Size
XL
